### ISSUE TITLE
Missing tags? ... e.g., v0.11.4

### ISSUE THREAD

**Issue by rickhg12hs** [mozilla/mp4parse-rust#267] opened 2021-01-20 05:41 UTC
I can't be sure since I'm a Rust noob, but I think the absence of `mp4parse v0.11.4` is causing `fselect` to have build errors for me.

Have previous tags been removed?

**Comment by baumanj** [comment] 2021-01-20 17:21
There never was an 0.11.4 tag. Our releases went straight from 0.10.1 to 0.11.5. I'm not familiar with `fselect`, but if you can say more about how your build is failing I might be able to help.

I'm going to close this issue since I don't think this is a defect in mp4parse, but feel free to keep posting here and we can reopen it if there are changes to be made.

**Closed by baumanj** 2021-01-20 17:21 UTC

**Comment by rickhg12hs** [comment] 2021-01-20 19:20
Is this the repo for the Rust crate [`mp4parse`](https://crates.io/crates/mp4parse)?  If so, that shows a version history which includes v0.11.4.

FYI, this is the `fselect` project I mentioned.  https://github.com/jhspetersson/fselect

Am I looking at the wrong `mp4parse`?

**Comment by baumanj** [comment] 2021-01-20 20:58
Oh weird. I think I must've made a mistake and published on crates.io without ever creating an appropriate tag in the github repo. I think yanking that version from crates.io would probably be the best thing. Any objection to me doing that?

**Comment by rickhg12hs** [comment] 2021-01-20 21:23
Wouldn't it be best to create the tags?  You can see the commit and when the versions were bumped in `Cargo.toml` histories like in https://github.com/mozilla/mp4parse-rust/commits/master/mp4parse/Cargo.toml

**Comment by baumanj** [comment] 2021-01-20 21:55
The problem is that [mp4parse was updated to 0.11.4](https://github.com/mozilla/mp4parse-rust/commit/e6549a1d231f8d46416d2b85940c7ad61ddcff46) in October 2019 and [mp4parse_capi was updated to 0.11.4](https://github.com/mozilla/mp4parse-rust/commit/79f5bd9f0998ad93d137da21a552b94c9cf835c1) in April 2020, so there's not a good point to put in a tag on the repo that covers both. That was my mistake and I'll be careful to avoid making it again going forward. To avoid confusion, I think the best thing is to get rid of the 0.11.4 versions from crates.io. There isn't anything specific to that release that you need is there? 0.11.5 should be superior in every way.

**Comment by rickhg12hs** [comment] 2021-01-20 22:47
Well, v0.11.4 has `mp4parse::MediaContext::new()` but v0.11.5 doesn't ... which happens to break `fselect` builds since its `Cargo.toml` has only `mp4parse = "0.11"`.  I suppose `fselect` developers will need to update their `Cargo.toml` to workaround this breaking change.

**Comment by rickhg12hs** [comment] 2021-01-21 10:04
FYI, `fselect` has upgraded its `mp4parse` usage to v0.11.5 now.  https://github.com/jhspetersson/fselect/commit/2b7141b755d2885dedb001d3414463fea6edfc53
